### ISSUE TITLE
Intención de compra

### ISSUE THREAD

**Issue by MBMaldonado** [aljavier/agromarketRD#1]
@aljavier 
Después de que el **Comprador** haga una demanda y el **Productor** cree una oferta (ya sea a la demanda o general), ¿cómo es que llegará a hacerse una intención de compra? ¿Cuáles serían los pasos del **Comprador** para concretizar la intención de compra?

**Comment by aljavier** [comment]
Buena pregunta. Ya Joel Addon me preguntaba algo parecido. Por ello, actualize el README. Ahi digo que me falta crear unos dos metodos, necesito uno donde se haga una especie de firma de la compra, osea, tanto el comprador como el productor deberan **confirmar** llamando a ese metodo.

Ahi quedaria cerrada la venta, se inactivarian y pasarian al historico. 

Ando trabajando en algo ahora mismo, pero buscare la forma de poder crear esos metodos y actualizar todo lo correspondiente hoy mismo.

**Comment by aljavier** [comment]
@MBMaldonado chequea
1. El productor puede hacer una oferta abierta en el Mercado, sin una demanda.
2. El productor puede hacerle una oferta a una demanda creada por un comprador
      1. Primero crearía una oferta.
      2. Luego la linkea a la demanda (metodo createDeal, el cual crea la intención de compra).
3. El comprador puede hacer una demanda abierta en el Mercado.
4. También puede a partir de una oferta crear una intención de compra.
     1. Crearía la demanda.
     2. La linkearía a la oferta con el mismo método que en el caso del productor.
4. Ambos luego de que uno de los dos cree la intención de compra tendría que firmar para culminar todo (llamar el método SignDeal).

De este modo, cualquiera de las partes podría hacer la intención de compra. Luego de eso ambas partes tendrían que firmar la *transacción* para culminar la venta/compra. Mira [aquí](https://github.com/aljavier/agromarketRD#métodos-a-crear-proposal) he actualizado el README con los métodos que crearemos para culminar.

Saludos.

**Comment by MBMaldonado** [comment]
@aljavier 

Entendí todo, pero considero que una **intención de compra** debe ser realizada solo por el **Comprador**. Porque la **intención de compra** es el **Comprador** diciéndole al **Productor**: Mira, yo quiero comprarte esto, según la **oferta** que publicaste (ya sea una **oferta** que atendía a una **demanda** o no).  Porque el productor no compra, sino que vende, y con aceptar una **intención de compra** del **Comprador** ya estaría cumpliendo su function de vender.

Eso considero.

Saludos,

**Comment by aljavier** [comment]
@MBMaldonado 

Si lo que pasa es que tambien se ha querido que un comprador pueda hacer una demanda abierta a todo el mercado, asi evaluar las ofertas que le han hecho directamente. Entonces como ambos pueden hacer un llamado publico al mercado (oferta o demanda) mejor se hizo de esa manera, porque en todo caso la compra no se concreta ahí, si no que ambas partes deben **firmar**. Entiendo que el nombre **intención de compra** pueda ser un poco inadecuado si lo puede hacer tambien el vendedor, pero es un solo nombre.

**Comment by MBMaldonado** [comment]
@aljavier 
En ese sentido, te aseguro que más del 50% de los grupos (por no exagerar) estamos confusos con lo que en verdad se va a hacer y eso que hoy es casi jueves. Porque las cosas descritas por Jorge en el documento están muy diferente a lo que se está desarrollando en el servicio. Nosotros teníamos entendido que habían **intenciones de compra y venta**, luego entendimos que las **intenciones de ventas** en sí son las **ofertas**. Pero ahora sí que nos enrredaste a algunos más de lo que estábamos. Yo pedí XML a los Productores y Compradores y las **intenciones de compra** se las pedí solo a los Compradores, porque desde un inicio eso lo harían solo ellos.

Lo que tenemos armado cada vez más se aleja de la idea que vienes desarrollando del servicio, están saliendo cosas nuevas y eso nos mata a nosotros, porque todo lo que estamos haciendo tendremos que dar un giro muy diferente, ya que no está claro el papel de cada quien y eso es muy preocupante. **¡Faltan solo 2 días!**

Yo le comenté a  **Juan Adón** sobre que los **Prpoductores** pueden hacer **intenciones de compra** y se quedó igual que yo: **AHORA ES QUE NO ENTIENDO ESTO**.

No podemos así, estamos trabajando superficialmente y cada vez son los cambios, lo cual nos afecta solo a nosotros, porque ustedes con el servicio van desarrollándolo y haciendo sus cambios y lo tendrán todo listo, pero nosotros estamos **inciertos** hasta que digan **ya terminamos el web service**, pero al parecer cuando digan eso, de momento solo nos quedarán horas para entregar el proyecto final.

Analicen lo que están haciendo, pónganse claros en una sola cosa y no estén cambiando ni agregando nada ni suponiendo una mejor forma si ya se tiene planteado de otra, porque aunque para ustedes es nada, para nosotros es muchísimo, ya que ni tenemos en sí lo que nos devolverá o pedirá cada método del web service. Es decir, nosotros estamos desarrollando en suposiciones de que las cosas serán de una manera y, por lo que veo, estamos basados en suposiciones muy erradas y confusas, analizándolas desde el poco de información que tenemos.

Estoy seguro que si 1 grupo, además de **Auditoría**, está al tanto de ese documento **README** somos mucho...

**Comment by aljavier** [comment]
@MBMaldonado ok, lo tomare en cuenta. Hare los cambios para homologar todo con el documento. Aunque ahi a diferencia de que se pueden comprar mas productos (que no esta ahora) se puede hacer practicamente todo lo demas como indica el documento. Pero hare los cambios pertinentes y hare una especie de casos de usos mas tecnico para ayudar mejor ahi.

Entendia en cuanto al tema que era para la otra semana. En fin, entonces a terminarlo.

**Comment by MBMaldonado** [comment]
Hello @aljavier 

Ahora vi que colocaste el **README** conforme al documento, en cierto aspecto, pero ese cambio nos afecta bastante (como te dije anteriormente que los cambios nos matan). Cuando te dije que las cosas que están en el servicio no es lo del documento, era haciendo referencia para que veas cómo estamos trabajando. Yo ayer en la madrugada envié un archivo al grupo de Whatsapp con los layouts de los XML que los chicos me estarán enviando, los adapté al modelo que tenías aquí (al momento de realizar el documento), pero ahora acabas de cambiar el modelo más o menos a lo que está en el document que hizo Jorge (que por cierto, yo había colocado algo de Auditoria y al parecer Jorge no ha hecho un merge de los Forks porque nuestro cambio no se ve en el principal). Por ejemplo, ahora tienes definido que sería **n productos** en las intenciones, lo cual habíamos hablado que sería de **un solo producto** y así mandé el layout de XML.

En ese sentido, vamos a parar de desarrollar y a tomarnos un momento para definir un modelo y así estamos todos sincronizados. Te pido, por favor, que tomes un tiempo el día de hoy (lo más temprano posible) y hagas un diagrama de flujo para nosotros entender cómo sera el proceso (definitivo) o los pasos que seguirá la aplicación (es decir, qué se hace primero, qué le sigue, qué se enlaza con qué y cómo y quién cerrará la venta). Si no puedes en un diagrama, escribe un algoritmo o algo donde podamos ver la secuencia de pasos, y si colocas los atributos escenciales que tendrá cada parte, más completo sería.

Créeme que si huibiese sido para la semana próxima, no estaríamos atacándo a tu equipo con respecto al web service, que desde el principio solo pedíamos al menos la estructura del servicio, para ir trabajando y nosotros simularlo y luego adaptarlo.

**Por favor**, como te dije, deten el desarrollo, tómate unos minutos, define el flujo de los métodos, sus actores y los mínimos atributos requeridos (acercándote al documento de Jorge con lo más sencillo posible, porque no hay tiempo para complicaciones ni arquitecturas bien definidas). Porque como te digo, los cambios primeros nos mataban, pero nos estábamos adaptando a lo que tenías, pero ahora volviste a una posición un poco acercada al documento y eso nos hace volver atrás (en el caso de **Auditoría** tendremos que adecuar los layouts que ya mandamos y que no sé si ya otro grupo lo había trabajado así).

Sé que he escrito mucho, pero quiero que se entienda. Por lo tanto, es que vuelvo y te repito: **siéntate unos minutos a hacer un análisis de lo que sería la forma más sencilla, tomando en cuenta el documento, (y la parte de auditoria que está en un FORK del mismo documento), descríbela de la forma que te indiqué anteriormente.** Y versa que ahí todos nos alineamos y podemos salir a camino.

Saludos,

**Comment by aljavier** [comment]
Sí @MBMaldonado lo que pasa es que la versión inicial del WS se hice en "tiempos de cólera" y casi ni caso hice del doc de @JArmando entonces es precisamente haciendo caso a tus propios comentarios y otros que lo he redefinido para que este acorde el documento. De hecho, le he quitado complejidad al WS ahora.
