### ISSUE TITLE
Métodos para Auditoría

### ISSUE THREAD

**Issue by MBMaldonado** [aljavier/agromarketRD#2]
@aljavier 
¿Tienen alguna información o adelanto respecto a los métodos que **Auditoría** estaría consumiento?

**Comment by aljavier** [comment]
Sí. He actualizado el [README](https://github.com/aljavier/agromarketRD#métodos-a-crear-proposal) el último método que se ve ahí estaría disponible para **Auditoría** también. Sólo que en el caso de auditaría devolveríamos todas las ventas finalizadas de todos los compradores/vendedores.

Si tienes alguna observación soy todo oídos (ojos).

Saludos.

**Comment by MBMaldonado** [comment]
@aljavier 
Acabo de leer el ultimo método que es lo que iría para **Auditoria**. Y sobre dicho método tengo lo siguiente:

- Para **Auditoria** consideramos debes colocarnos **id del producto**, **fecha creación** (fecha donde se concretizó la venta), **unidad** y el **precio por unidad**, ya que recuerda que nosotros no consumiremos los demás servicios para obtener esas informaciones y relacionarlas y obtener esos campos que te mencionamos anteriormente.

Saludos,

**Comment by aljavier** [comment]
@MBMaldonado tienes razón, no lo había incluído porque se podrían obtener con otros métodos, pero cierto que ustedes sólo consumirán un metodo. Muy buena observación. Haré los cambios correspondientes.

**Comment by aljavier** [comment]
@MBMaldonado ojo aqui, los productos en el WS lo estamos manejando por codigo no por id, para evitar problemas por cambios en el db. Asi cada quien podria tener su copia de catologo con el id que quieran, pero el codigo debe ser el que usa **Mercado**.
