### ISSUE TITLE
Use Cases file

### ISSUE THREAD

**Issue by MBMaldonado** [aljavier/agromarketRD#3]
Hello @aljavier 

En el documento principal nosotros colocamos hace un buen tiempo (exactamente hace dos semanas) la parte de **Auditoría.** Luego le hicimos unas modificaciones por unas aclaraciones que @JArmando me había ofrecido junto con **Juan Adón**, pero eso lo hicimos en un **FORK** al documento, ya que no podíamos modificar directamente el mismo. En ese sentido, me habían dicho (porque no uso mucho github) que el dueño del documento debe hacer un merge para que mis cambios se vean en el documento principal, de no ser así yo no sé, porque como dije no utilizo mucho github.

Ahora mismo acabo de modificarlo para corregir unos errores que tienía, pero en nada cambió la escencia de lo que **Mercado, Compradores** y **Productores** nos van a compartir, ya que fue en la parte de **Reportes y/o Estadísticas.** Claro está, esa información está según lo que en el curso se había acordado y lo que decía el documento incialmente.

Los cambios colocados por **Auditoría** están [aquí](https://gist.github.com/MBMaldonado/b145f5d8f5c71070936cf2e833d9a2a1).

**Comment by aljavier** [comment]
Bien, le echaré un ojo.
